name = "kuroco-social-network"
compatibility_date = "2022-06-10"

zone_id = ""
account_id = ""
workers_dev = true
main = "./build/index.js"

[site]
bucket = "./public"

[build]
command = "npm run build"

[build.upload]
format="service-worker"
